package com.bootcamp.guessinggame;

import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Player player = new Player();
        Computer computer = new Computer();

        System.out.println("Welcome to \"Guess the Number\", " + player.getName() + "!");
        System.out.println("You need to guess a number between 1 and 10 generated by " + computer.getName() + "!");

        boolean playAgain;
        do {
            boolean correctGuess = false;

            while (!correctGuess) {
                player.makeGuess();
                correctGuess = computer.checkGuess(player.getGuess());
            }

            System.out.print("Do you want to play again? (yes/no): ");
            String response = scanner.nextLine().trim().toLowerCase();
            playAgain = response.equals("yes") || response.equals("y");
        } while (playAgain);

        System.out.println("Thank you for playing!");
    }
}
